### PR TITLE
Mentors sorted.

### PR DESCRIPTION
**Pull request by hemanth**
Sorted them all, must be automated with a git hook :)

### CODE REVIEW

**Comment by jasonrhodes** [comment]
Thanks @hemanth. I'll just say that I'm not sure this is worth the maintenance right now, considering that we're going to move this list down the README in favor of language directed at mentees at the top, and we're going to instruct potential mentees to post questions as issues or on Gitter, and then mentors will jump in and suggest partnerships. If we go that way, searching or scanning the list of mentors is less important.

Let's hold off on this until we go through the trial period mentioned in #26 unless someone else has other ideas/opinions?

**Comment by hemanth** [comment]
Sure! Completely agree.

**Comment by jasonrhodes** [comment]
Closing for now, we'll re-open and discuss again if we decide to go this route later. Thanks again for your work, @hemanth!

**Comment by hemanth** [comment]
:+1:

**Pull request closed without merging**
