### PR TITLE
Fixed wrong URL for issue #49

### PR DESCRIPTION
**Pull request by ifraixedes**
I've fixed wrong URL for issue #49 and replaced by anchor than a raw URL

### CODE REVIEW

**Comment by jasonrhodes** [comment]
Hey thanks! Did you test this change? It looks like I forgot the ".com" originally but it doesn't look like that's been added so this change may still not work. 

Alternately, you could use the <org>/<repo>/#49 syntax which will auto-link. 

Wanna update so I can merge? You can amend and force push your commit.

**Comment by ifraixedes** [comment]
Yeah, I thought that I tested, but obviously, I didn't.
I'm trying to use the autolink, but I cannot find what I have to type, I tried with (without tildes) `//#49`,`#49` and `[#49](//#49)` but they didn't work.

I don't know that it is the short version, can you tell me how?

Sorry for the silly issue.
Thanks

**Comment by jasonrhodes** [comment]
Haha my comment got html encoded. The auto link syntax is {org or user}/{repo}/#49

**Comment by ifraixedes** [comment]
I tried with that but I could make it to work; I think that it work for commit messages, issues' comments, etc, however it does not apply for Markdown docs into the repo, is it?

By the way, I updated with the absolute URL

**Comment by jasonrhodes** [comment]
Ah that might be right, thanks!

**Pull request merged**
